# Generated by Django 5.0.4 on 2024-05-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech_is_simple', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialistPatient',
        ),
    ]
