# Generated by Django 5.0.4 on 2024-04-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_is_simple_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='ANONYMUS', max_length=255),
        ),
    ]
