# Generated by Django 5.0.4 on 2024-05-03 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_is_simple_auth', '0004_specialist_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speech_is_simple_auth.patient')),
                ('specialistId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speech_is_simple_auth.specialist')),
            ],
        ),
    ]
