# Generated by Django 5.0.4 on 2024-05-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech_is_simple_auth', '0005_specialistpatient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialistpatient',
            old_name='patientId',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='specialistpatient',
            old_name='specialistId',
            new_name='specialist',
        ),
    ]
